In [ ]:
import numpy as np
import pandas as pd

# To convert a NumPy array to a Pandas series:

In [ ]:
array = np.array(['A', 'a', 'b', 'h', 'a']) 
series = pd.Series(array) 
print(series)

# To convert the first column of a DataFrame as a Series:

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3],
                   'B': [4, 5, 6]})

# Use .ix[] to select the first column as a Series
series = df.iloc[:, 0]
print(series)

# To create the mean and standard deviation of the data of a given Series

In [ ]:
s = pd.Series(data = [5, 9, 8, 5, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3])
# finding the mean
print(s.mean())
# finding the Standard deviation
print(s.std())

# To sort a given Series:

In [ ]:
sr = pd.Series([19.5, 16.8, 22.78, 20.124, 18.1002])
# Print the series
print(sr)
# sort the values in descending order
print(sr.sort_values(ascending = False))